---
title: "FBS subs"
output: html_document
date: "2023-05-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
Book2 <- read_excel("C:/Users/Liily/Desktop/csvformat.xlsx", 
    col_names = FALSE)
Book2 <- subset(Book2, apply(Book2, 1, function(x) !all(x == 0)))
na.omit(Book2)

CD9UC <- na.omit(as.numeric(unlist(Book2 [4])))
CD9TEIR <- na.omit(as.numeric(unlist(Book2 [8])))
CD9Dyna <- na.omit(as.numeric(unlist(Book2 [12])))
CD9PEG <- na.omit(as.numeric(unlist(Book2 [16])))
CD9Gold <- na.omit(as.numeric(unlist(Book2 [20])))

CD9UCevMBR <- na.omit(as.numeric(unlist(Book2 [5])))
CD9TEIRevMBR <- na.omit(as.numeric(unlist(Book2 [9])))
CD9DynaevMBR <- na.omit(as.numeric(unlist(Book2 [13])))
CD9PEGevMBR <- na.omit(as.numeric(unlist(Book2 [17])))
CD9GoldevMBR <- na.omit(as.numeric(unlist(Book2 [21])))

PuroCD9UC <- na.omit(as.numeric(unlist(Book2[25])))
PuroCD9TEIR <- na.omit(as.numeric(unlist(Book2[28])))
PuroCD9Dyna <- na.omit(as.numeric(unlist(Book2[31])))
PuroCD9PEG <- na.omit(as.numeric(unlist(Book2[34])))
PuroCD9Gold <- na.omit(as.numeric(unlist(Book2[37])))

PuroIsoUc <- na.omit(as.numeric(unlist(Book2[41])))
PuroIsoTEIR <- na.omit(as.numeric(unlist(Book2[44])))
PuroIsoDyna <- na.omit(as.numeric(unlist(Book2[47])))
PuroIsoPEG <- na.omit(as.numeric(unlist(Book2[50])))
PuroIsoGold <- na.omit(as.numeric(unlist(Book2[53])))


my_list <- list(CD9UC, CD9TEIR, CD9Dyna, CD9Dyna, CD9PEG, CD9Gold, CD9UCevMBR, CD9TEIRevMBR, CD9DynaevMBR, CD9PEGevMBR, CD9GoldevMBR, PuroCD9UC, PuroCD9TEIR, PuroCD9Dyna, PuroCD9PEG, PuroCD9Gold, PuroIsoUc, PuroIsoTEIR, PuroIsoDyna, PuroIsoPEG, PuroIsoGold)
CD9MKLPOvp_list <- list(CD9UC, CD9TEIR, CD9Dyna, CD9Dyna, CD9PEG, CD9Gold)
EvMBR_list <- list(CD9UCevMBR, CD9TEIRevMBR, CD9DynaevMBR, CD9PEGevMBR, CD9GoldevMBR)
PC9_list <- list(PuroCD9UC, PuroCD9TEIR, PuroCD9Dyna, PuroCD9PEG, PuroCD9Gold)
PuroIso_list <- list(PuroIsoUc, PuroIsoTEIR, PuroIsoDyna, PuroIsoPEG, PuroIsoGold)
```

## R Markdown

summary of data

```{r cars}
for (i in 1:length(my_list)) {
  cat("Summary for", names(my_list)[i], ":\n")
  print(summary(my_list[[i]]))
  cat("\n")
}
```

## Including Plots

Histograms for data sets

```{r pressure, echo=FALSE}
for (i in 1:length(my_list)) {
  if (!is.numeric(my_list[[i]]) || all(is.na(my_list[[i]]))) {
    next  # Skip non-numeric or empty vectors
  }
  hist(my_list[[i]], main = paste("Histogram"), breaks = 5, freq = TRUE)
}
```

##whitneymann test
```{r whitneymann, echo=FALSE}
wilcox.test(CD9UC, CD9TEIR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(CD9UC, CD9Dyna, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(CD9UC, CD9PEG, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(CD9UC, CD9Gold, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)

wilcox.test(CD9UCevMBR, CD9TEIRevMBR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(CD9UCevMBR, CD9DynaevMBR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(CD9UCevMBR, CD9PEGevMBR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(CD9UCevMBR, CD9GoldevMBR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(CD9UCevMBR, CD9TEIRevMBR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)

wilcox.test(PuroCD9UC, PuroCD9TEIR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(PuroCD9UC, PuroCD9Dyna, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(PuroCD9UC, PuroCD9Gold, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(PuroCD9UC, PuroCD9PEG, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)

wilcox.test(PuroIsoUc, PuroIsoTEIR, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(PuroIsoUc, PuroIsoDyna, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(PuroIsoUc, PuroIsoPEG, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)
wilcox.test(PuroIsoUc, PuroIsoGold, paired = FALSE, alternative = ("two.sided"), exact = TRUE, conf.int = TRUE, conf.level = 0.95)

```